spring:
  application:
    name: crudChad
  datasource:
    url: jdbc:postgresql://localhost:5432/megacrud
    username: postgres
    password: 123
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/sandbox
        registration:
          crud-chad:
            provider: keycloak
            client-id: crud-chad
            authorization-grant-type: client_credentials
            client-secret: vjbYD7005JZTtGJN1yESkhzIoy9g78X8
            scope:
              - openid
              - microprofile-jwt
              - posts
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/sandbox
server:
  port: 8080

app:
  minio:
    bucketname: catalog-images
    region: eu-east
    url: http://localhost:9000
    expiry: 3600
    credentials:
      name: minioadmin
      secret: minioadmin
  keycloak:
    realm: sandbox
    client-id: crud-chad
    auth-server-url: http://localhost:8082
    credentials:
      secret: vjbYD7005JZTtGJN1yESkhzIoy9g78X8
